# Generated by Django 4.2.7 on 2023-11-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_text', models.CharField(max_length=30)),
                ('batafsil', models.CharField(max_length=30)),
                ('sana', models.DateField()),
                ('boshlanmagan', models.CharField(max_length=30)),
            ],
        ),
    ]
